version: "3.8"
services:
  postgres:
    container_name: postgres-container
    image: ${POSTGRES_DOCKER_SERVICE_NAME}:database
    build:
      context: ../
      dockerfile: ./ci/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_DOCKER_HOST_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    user: "postgres"
    restart: always

volumes:
  postgres_data:
