version: "3.8"
services:
  postgres:
    container_name: postgres-container
    image: ${POSTGRES_DOCKER_SERVICE_NAME}:database
    build:
      context: ../
      dockerfile: ./ci/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_DOCKER_HOST_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    user: "postgres"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - portfolio-backend-network

networks:
  portfolio-backend-network:
    external: true

volumes:
  postgres_data:
    driver: local
