import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="google-site-verification"
          content="WrgXhDJoxCGujyLnFUO8SgIZCiXVWzwutKiQQujBiY8"
        />
        <meta
          name="naver-site-verification"
          content="4909b4bb612edd28d0f591516306e500cd19b359"
        />
      </Head>
    </>
  );
}
