name: ${APP_DOCKER_SERVICE_NAME} # container name
services:
  frontend:
    container_name: ${APP_DOCKER_SERVICE_NAME} # container unit name
    build:
      context: ../../
      dockerfile: ./ci/dockerfiles/Dockerfile
    volumes:
      - ../../src:/usr/src/app/src
    image: ${APP_DOCKER_SERVICE_NAME}:frontend # image name
    ports:
      - ${APP_DOCKER_HOST_PORT}:${PORT}
    environment:
      - PORT=${PORT}
