name: production
services:
  server:
    build:
      context: ../../
      dockerfile: ./ci/dockerfiles/Dockerfile
      target: production
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_DOCKER_HOST_PORT}:${PORT}

  nginx:
    image: nginx:latest
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_DOCKER_HOST_PORT}:${NGINX_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - server
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
