name: production
services:
  server:
    build:
      context: ../../
      dockerfile: ./ci/dockerfiles/Dockerfile
      target: production
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_DOCKER_HOST_PORT}:${PORT}
