version: "3.8"
services:
  server:
    container_name: portfolio-server_prd
    build:
      context: ../../
      dockerfile: ./ci/dockerfiles/Dockerfile
    image: ${APP_DOCKER_SERVICE_NAME}:backend
    environment:
      - NODE_ENV=production
    volumes:
      - ../../envs:/usr/src/app/envs
    ports:
      - ${APP_DOCKER_HOST_PORT}:${PORT}
    command: ["npm", "run", "start"]
    networks:
      - portfolio-backend-network

networks:
  portfolio-backend-network:
    external: true
