name: production
services:
  server:
    build:
      context: ../../
      dockerfile: ./ci/dockerfiles/Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - ../../envs:/usr/src/app/envs
    ports:
      - ${APP_DOCKER_HOST_PORT}:${PORT}
    command: ["npm", "run", "start"]
    networks:
      - portfolio-backend-network

networks:
  portfolio-backend-network:
    external: true
