name: portfolio-backend
services:
  server:
    build:
      context: ../../
      dockerfile: ./ci/dockerfiles/Dockerfile
      target: local
    volumes:
      - ../../src:/usr/src/app/src
      - ../../node_modules:/usr/src/app/node_modules
    ports:
      - ${APP_DOCKER_HOST_PORT}:${PORT}
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_DOCKER_HOST_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
