name: portfolio-backend-develop
services:
  portfolio-backend-develop:
    build:
      context: ../../
      dockerfile: ./ci/local/Dockerfile
      target: local
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_DOCKER_HOST_PORT}:${PORT}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_DOCKER_HOST_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
