name: portfolio-database
services:
  database:
    build:
      context: ../../
      dockerfile: ./ci/dockerfiles/Dockerfile.db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - ${POSTGRES_DOCKER_HOST_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
