name: blog build and deploy
on:
  push:
    paths:
      - "blog/**"
    branches:
      - main
  pull_request:
    paths:
      - "blog/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via docker-compose
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $SERVER_USER@$SERVER_IP << 'EOF'
            cd /home/doyeon/portfolio/blog
            git fetch origin
            git merge origin/main
            sudo docker-compose --env-file ./envs/.env.production -f ./ci/composes/docker-compose.yaml up --build -d
          EOF
