name: backend build and deploy
on:
  push:
    paths:
      - "portfolio-server/**"
    branches:
      - main
  pull_request:
    paths:
      - "portfolio-server/**"
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.AZURE_VM_IP }} << 'EOF'
            cd /home/doyeon/portfolio
            git pull origin main  # 최신 코드 가져오기
            cd portfolio-server
            rm -rf node_modules
            rm -rf dist
            npm install
            npm run build
            docker-compose -f ./ci/composes/docker-compose.yaml --env-file ./envs/.env.production up --build
          EOF
        env:
          AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
