name: backend build and deploy
on:
  push:
    paths:
      - "portfolio-server/**"
    branches:
      - main
  pull_request:
    paths:
      - "portfolio-server/**"
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Navigate to backend directory
        run: cd portfolio-server # 백엔드 디렉토리로 이동

