name: backend build and deploy
on:
  push:
    paths:
      - "portfolio-server/**"
    branches:
      - main
  pull_request:
    paths:
      - "portfolio-server/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64] # 등록한 runner의 레이블 사용

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy via docker-compose
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $SERVER_USER@$SERVER_IP << 'EOF'
            cd /home/doyeon/portfolio
            git fetch origin
            git merge origin/main
            cd portfolio-server
            docker stop portfolio-server_prd
            docker rm portfolio-server_prd
            docker rmi portfolio-server:backend
            docker-compose --env-file ./envs/.env.production -f ./ci/composes/docker-compose.yaml up -d --build
          EOF
